kubectl apply -f pod1-deployment.yaml
kubectl apply -f pod2-deployment.yaml
kubectl apply -f pod3-deployment.yaml
kubectl apply -f pod4-deployment.yaml
kubectl apply -f pod5-deployment.yaml
kubectl apply -f pod6-deployment.yaml
kubectl apply -f pod7-deployment.yaml
kubectl apply -f pod8-deployment.yaml
kubectl apply -f pod9-deployment.yaml