docker build --pull --rm -f "Dockerfile.pod1" -t jemiaymen/pod1 .
docker build --pull --rm -f "Dockerfile.pod2" -t jemiaymen/pod2 .
docker build --pull --rm -f "Dockerfile.pod3" -t jemiaymen/pod3 .
docker build --pull --rm -f "Dockerfile.pod4" -t jemiaymen/pod4 .
docker build --pull --rm -f "Dockerfile.pod5" -t jemiaymen/pod5 .
docker build --pull --rm -f "Dockerfile.pod6" -t jemiaymen/pod6 .
docker build --pull --rm -f "Dockerfile.pod7" -t jemiaymen/pod7 .
docker build --pull --rm -f "Dockerfile.pod8" -t jemiaymen/pod8 .
docker build --pull --rm -f "Dockerfile.pod9" -t jemiaymen/pod9 .