FROM jemiaymen/scapy:2.4

RUN apt update -y && apt upgrade -y && apt-get install tcpdump -y ; apt-get install tcpreplay -y ;  apt clean

WORKDIR /app
COPY pod7_lawfull_intercept.py /app/pod.py
CMD [ "python" ,"/app/pod.py" ]