FROM jemiaymen/scapy:2.4
RUN apt-get update && apt-get install -y tcpdump tcpreplay

WORKDIR /app

COPY tcp_latency /app/tcp_latency
COPY tcpdump_tcpreplay.py /app/pod.py
CMD [ "python" ,"/app/pod.py" ]