apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: p2
  name: p2
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: p2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
        kompose.service.type: LoadBalancer
        "cni.projectcalico.org/ipAddrs": "[\"10.244.246.129\"]"
      creationTimestamp: null
      labels:
        io.kompose.service: p2
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          image: myriamtrad/tcpreplay
          imagePullPolicy: Always
          name: tcpreplay
          resources: {}
          command: ["/bin/sh","-c"]
          args: ["/app/tcpreplay.sh && sleep inf"]
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
      volumes:
        - name: cache-volume
          hostPath:
            path: /home/lkn/myriam
      
      
      restartPolicy: Always
status: {}
