apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: p3
  name: p3
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: p3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
        kompose.service.type: LoadBalancer
        "cni.projectcalico.org/ipAddrs": "[\"10.244.246.130\"]"
      creationTimestamp: null
      labels:
        io.kompose.service: p3
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          image: myriamtrad/tcpdump
          imagePullPolicy: Always
          name: tcpdump
          resources: {}
          command: ["/bin/sh","-c"]
          args: ["tcpdump -i eth0 -w /app/target.pcap -c 1 dst 10.244.246.130 && sleep inf"]

      restartPolicy: Always
status: {}
