apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pod10
  name: pod10
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pod10
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
        "cni.projectcalico.org/ipAddrs": "[\"10.244.246.138\"]"
      creationTimestamp: null
      labels:
        io.kompose.service: pod10
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: myriamtrad/tcpreplaysender
          imagePullPolicy: Always
          name: tcpreplaysender
          resources: {}
      restartPolicy: Always
status: {}
