apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pod1
  name: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pod1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pod1
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: myriamtrad/scapy-pod1
          name: sender
          resources: {}
      restartPolicy: Always
status: {}
