apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pod5
  name: pod5
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pod5
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pod5
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: jemiaymen/pod5
          name: qos
          resources: {}
      restartPolicy: Always
status: {}
