docker push jemiaymen/pod1
docker push jemiaymen/pod2
docker push jemiaymen/pod3
docker push jemiaymen/pod4
docker push jemiaymen/pod5
docker push jemiaymen/pod6
docker push jemiaymen/pod7
docker push jemiaymen/pod8
docker push jemiaymen/pod9